version: '3.6'

services:

  todo-app-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: todo-app-server
    depends_on:
      - todo-app-db
    environment:
      NODE_ENV: production
    labels:
      group: "todo-app"
      name: "todo-app-net"
    networks:
      - todo-app-net
    restart: on-failure
    ports:
      - 8080:8080

  todo-app-db:
    command: mongod --auth
    container_name: todo-app-db
    environment:
      - DB_NAME
      - DB_PASSWORD
      - DB_USERNAME
    image: mongo:4.2-bionic
    labels:
      group: "todo-app"
      name: "todo-app-net"
    networks:
      - todo-app-net
    restart: on-failure
    volumes:
      - todo-app-db-data:/data/db
      - ./mongodb/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 27017:27017

networks:
  todo-app-net:
    driver: bridge
    labels:
      group: "todo-app"
      name: "todo-app-net"
    name: todo-app-net

volumes:
  todo-app-db-data:
    driver: local
    labels:
      group: "todo-app"
      name: "todo-app-db-data"
    name: todo-app-db-data